language: java

jdk:
  - openjdk7

env:
  - TERM=dumb

before_script:
  - mysql -e "create database petstore_test;"
  - mysql -e "create user 'testbot'@'localhost' identified by 'petstore'";
  - mysql -u root -e "grant all on petstore_test.* to 'testbot'@'localhost'";
  
deploy:
  provider: heroku
  app: apetshop
  api_key: ed0425bf-635d-4af9-9ad1-cd89f4d6d3d7